using IxcNet.Interfaces;

namespace IxcNet.ViewModels.Sistema.Cadastros.Clientes
{
    public class ClienteContratoViewModel : INamedModel
    {
        public string? ModelName => "cliente_contrato";

        public string? id { get; set; }
        public string? id_cliente { get; set; }
        public string? id_filial { get; set; }
        public string? status { get; set; }
        public string? status_internet { get; set; }
        public string? contrato { get; set; }
        public string? data { get; set; }
        public string? data_assinatura { get; set; }
        public string? data_ativacao { get; set; }
        public string? data_renovacao { get; set; }
        public string? data_expiracao { get; set; }
        public string? pago_ate_data { get; set; }
        public string? bloqueio_automatico { get; set; }
        public string? isentar_contrato { get; set; }
        public string? id_vd_contrato { get; set; }
        public string? endereco { get; set; }
        public string? numero { get; set; }
        public string? bairro { get; set; }
        public string? complemento { get; set; }
        public string? cep { get; set; }
        public string? cidade { get; set; }
        public string? tipo { get; set; }
        public string? comissao { get; set; }
        public string? descricao_aux_plano_venda { get; set; }
        public string? aviso_atraso { get; set; }
        public string? id_tipo_contrato { get; set; }
        public string? id_carteira_cobranca { get; set; }
        public string? id_modelo { get; set; }
        public string? status_velocidade { get; set; }
        public string? id_vendedor { get; set; }
        public string? cc_previsao { get; set; }
        public string? nao_avisar_ate { get; set; }
        public string? nao_bloquear_ate { get; set; }
        public string? id_tipo_documento { get; set; }
        public string? tipo_doc_opc { get; set; }
        public string? tipo_doc_opc2 { get; set; }
        public string? tipo_doc_opc3 { get; set; }
        public string? tipo_doc_opc4 { get; set; }
        public string? desconto_fidelidade { get; set; }
        public string? taxa_improdutiva { get; set; }
        public string? desbloqueio_confianca { get; set; }
        public string? desbloqueio_confianca_ativo { get; set; }
        public string? data_negativacao { get; set; }
        public string? data_acesso_desativado { get; set; }
        public string? motivo_cancelamento { get; set; }
        public string? data_cancelamento { get; set; }
        public string? obs_cancelamento { get; set; }
        public string? id_vendedor_ativ { get; set; }
        public string? fidelidade { get; set; }
        public string? tipo_cobranca { get; set; }
        public string? id_responsavel { get; set; }
        public string? taxa_instalacao { get; set; }
        public string? protocolo_negativacao { get; set; }
        public string? dt_ult_bloq_auto { get; set; }
        public string? dt_ult_bloq_manual { get; set; }
        public string? dt_ult_desbloq_auto { get; set; }
        public string? dt_ult_desbloq_manual { get; set; }
        public string? dt_ult_des_bloq_conf { get; set; }
        public string? dt_ult_ativacao { get; set; }
        public string? dt_ult_finan_atraso { get; set; }
        public string? dt_utl_negativacao { get; set; }
        public string? data_cadastro_sistema { get; set; }
        public string? ultima_atualizacao { get; set; }
        public string? renovacao_automatica { get; set; }
        public string? id_motivo_inclusao { get; set; }
        public string? motivo_inclusao { get; set; }
        public string? liberacao_bloqueio_manual { get; set; }
        public string? contrato_suspenso { get; set; }
        public string? ativacao_numero_parcelas { get; set; }
        public string? ativacao_vencimentos { get; set; }
        public string? ativacao_valor_parcela { get; set; }
        public string? id_tipo_doc_ativ { get; set; }
        public string? id_produto_ativ { get; set; }
        public string? id_cond_pag_ativ { get; set; }
        public string? endereco_padrao_cliente { get; set; }
        public string? referencia { get; set; }
        public string? id_condominio { get; set; }
        public string? nf_info_adicionais { get; set; }
        public string? assinatura_digital { get; set; }
        public string? tipo_produtos_plano { get; set; }
        public string? bloco { get; set; }
        public string? apartamento { get; set; }
        public string? latitude { get; set; }
        public string? longitude { get; set; }
        public string? num_parcelas_atraso { get; set; }
        public string? dt_ult_desiste { get; set; }
        public string? id_contrato_principal { get; set; }
        public string? gerar_finan_assin_digital_contrato { get; set; }
        public string? credit_card_recorrente_token { get; set; }
        public string? credit_card_recorrente_bandeira_cartao { get; set; }
        public string? id_motivo_negativacao { get; set; }
        public string? obs_negativacao { get; set; }
        public string? restricao_auto_desbloqueio { get; set; }
        public string? motivo_restricao_auto_desbloq { get; set; }
        public string? nao_susp_parc_ate { get; set; }
        public string? liberacao_suspensao_parcial { get; set; }
        public string? utilizando_auto_libera_susp_parc { get; set; }
        public string? restricao_auto_libera_susp_parcial { get; set; }
        public string? motivo_restri_auto_libera_parc { get; set; }
        public string? data_inicial_suspensao { get; set; }
        public string? data_final_suspensao { get; set; }
        public string? data_retomada_contrato { get; set; }
        public string? dt_ult_liberacao_susp_parc { get; set; }
        public string? base_geracao_tipo_doc { get; set; }
        public string? integracao_assinatura_digital { get; set; }
        public string? url_assinatura_digital { get; set; }
        public string? token_assinatura_digital { get; set; }
        public string? testemunha_assinatura_digital { get; set; }
        public string? document_photo { get; set; }
        public string? selfie_photo { get; set; }
        public string? tipo_localidade { get; set; }
        public string? estrato_social_col { get; set; }
        public string? agrupar_financeiro_contrato { get; set; }
        public string? status_recorrencia { get; set; }
        public string? id_instalador { get; set; }
        public string? indicacao_contrato_id { get; set; }
        public string? id_indexador_reajuste { get; set; }
        public string? data_desistencia { get; set; }
        public string? motivo_desistencia { get; set; }
        public string? obs_desistencia { get; set; }
        public string? obs_contrato { get; set; }
        public string? alerta_contrato { get; set; }
        public string? ids_contratos_recorrencia { get; set; }
        public string? id_responsavel_desistencia { get; set; }
        public string? id_responsavel_cancelamento { get; set; }
        public string? id_responsavel_negativacao { get; set; }
        public string? origem_cancelamento { get; set; }
        public string? situacao_financeira_contrato { get; set; }
        public string? aplicar_desconto_tempo_bloqueio { get; set; }
        public string? tempo_permanencia { get; set; }
        public string? avalista_1 { get; set; }
        public string? avalista_2 { get; set; }
    }
}
